name: Build Project

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build
        run: |
          xmake repo -u
          xmake f -m release -y
          xmake -y

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Locale-Emulator-Plus-Release
          path: build/windows/
